# Generated by Django 4.2.4 on 2023-10-30 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dados_contrato',
            fields=[
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('r_m', models.CharField(choices=[('I', 'Interior'), ('L', 'Litoral'), ('M', 'Metropolitana')], max_length=1, verbose_name='Diretoria:')),
                ('inserido', models.DateTimeField(auto_now_add=True, verbose_name='Inserido em:')),
                ('cadastrado_por', models.CharField(max_length=100)),
                ('numemro_contrato', models.CharField(max_length=10, unique=True, verbose_name='Número do Contrato:')),
                ('nome_contratada', models.CharField(max_length=100)),
                ('administrador', models.CharField(max_length=100)),
                ('superintendente', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('staff_1', models.CharField(max_length=100)),
                ('staff_2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tabela Dados do Contrato',
                'verbose_name_plural': 'Tabela Dados dos Contratos',
            },
        ),
        migrations.CreateModel(
            name='tb_log_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserido', models.DateTimeField(auto_now_add=True, verbose_name='Inserido em:')),
                ('inicio_envio', models.CharField(max_length=35, verbose_name='Inicio do envio do e-mail')),
                ('fim_envio', models.CharField(max_length=35, verbose_name='Fim do envio do e-mail')),
                ('total_enderecos', models.CharField(max_length=35, verbose_name='Quantidade de endereços selecionados')),
                ('total_de_envio', models.CharField(max_length=35, verbose_name='Quantidade de emails enviados')),
                ('tempo_envio', models.CharField(blank=True, max_length=9, null=True, verbose_name='tempo de execução')),
                ('status_tarefa', models.CharField(max_length=35, verbose_name='Status da tarefa')),
            ],
            options={
                'verbose_name': 'Tabela log de emil',
                'verbose_name_plural': 'Tabela log de emils',
            },
        ),
        migrations.CreateModel(
            name='tb_modalidade_interior',
            fields=[
                ('inserido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em:')),
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_ano_referencia', models.CharField(max_length=20)),
                ('inserido_por', models.CharField(max_length=100)),
                ('contrato', models.CharField(max_length=20)),
                ('idg_interior', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO GLOBAL (IDG)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('servicos_arsesp', models.DecimalField(decimal_places=2, help_text='SERVIÇOS ATENDIDOS NO PRAZO ARSESP', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrega_cadastro', models.DecimalField(decimal_places=2, help_text='ENTREGA DO CADASTRO E IMOBILIZAÇÃO', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acidente_trabalho', models.IntegerField(help_text='ACIDENTE DE TRABALHO (Quantidade)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('justificativa', models.TextField(help_text='Justifique os indicadores informados.', max_length=500)),
            ],
            options={
                'verbose_name': 'Tabela de Indicador Contrato Interior',
                'verbose_name_plural': 'Tabela de Indicadores Contratos Interior',
            },
        ),
        migrations.CreateModel(
            name='tb_modalidade_litoral',
            fields=[
                ('inserido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em:')),
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_ano_referencia', models.CharField(max_length=20)),
                ('inserido_por', models.CharField(max_length=100)),
                ('contrato', models.CharField(max_length=20)),
                ('idg_interior', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO GLOBAL (IDG)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('servicos_arsesp', models.DecimalField(decimal_places=2, help_text='SERVIÇOS ATENDIDOS NO PRAZO ARSESP', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrega_cadastro', models.DecimalField(decimal_places=2, help_text='ENTREGA DO CADASTRO E IMOBILIZAÇÃO', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acidente_trabalho', models.IntegerField(help_text='ACIDENTE DE TRABALHO (Quantidade)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('justificativa', models.TextField(help_text='Justifique os indicadores informados.', max_length=500)),
            ],
            options={
                'verbose_name': 'Tabela de Indicador Contrato Litoral',
                'verbose_name_plural': 'Tabela de Indicadores Contratos Litoral',
            },
        ),
        migrations.CreateModel(
            name='tb_modalidade_metropolitana',
            fields=[
                ('inserido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em:')),
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_ano_referencia', models.CharField(max_length=20)),
                ('inserido_por', models.CharField(max_length=100)),
                ('contrato', models.CharField(max_length=20)),
                ('idg', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO GLOBAL (IDG)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('isap', models.DecimalField(decimal_places=2, help_text='SERVIÇOS ATENDIDOS NO PRAZO (ISAP)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ida', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO NA ÁGUA (IDA)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ide', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO NA ESGOTO(IDE)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idr', models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO REPOSIÇÃO (IDR)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrega_cadastro', models.DecimalField(decimal_places=2, help_text='ENTREGA DO CADASTRO E IMOBILIZAÇÃO', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seg_capacitacao', models.DecimalField(decimal_places=2, help_text='SEGURANÇA E CAPACITAÇÃO', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('justificativa', models.TextField(help_text='Justifique os indicadores informados.', max_length=500)),
            ],
            options={
                'verbose_name': 'Tabela de Indicador Contrato Metropolitana',
                'verbose_name_plural': 'Tabela de Indicadores Contratos Metropolitana',
            },
        ),
        migrations.CreateModel(
            name='tb_referencia_contrato',
            fields=[
                ('inserido', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inserido em:')),
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_preenchimento', models.CharField(blank=True, max_length=100)),
                ('mes_ano_referencia', models.CharField(blank=True, max_length=20)),
                ('contrato', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('data_hora_preenchimento', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Tabela Mês/Ano Referencia',
                'verbose_name_plural': 'Tabela Mês/Ano Referencias',
            },
        ),
        migrations.CreateModel(
            name='tb_unidades',
            fields=[
                ('atualizado', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em:')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inserido', models.DateTimeField(auto_now_add=True, verbose_name='Inserido em:')),
                ('inserido_por', models.CharField(max_length=100)),
                ('num_unidade', models.IntegerField(unique=True)),
                ('sigla_unidade', models.CharField(max_length=10, unique=True)),
                ('nome_unidade', models.CharField(max_length=100, unique=True)),
                ('superintendente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tabela de Unidade',
                'verbose_name_plural': 'Tabela de Unidades',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacoes', models.BooleanField(default=True, verbose_name='Receber Notificações?')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabela de Perfil',
                'verbose_name_plural': 'Tabela de Perfis',
            },
        ),
    ]
