# Generated by Django 4.2.4 on 2023-10-31 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='entrega_cadastro',
            field=models.DecimalField(decimal_places=2, help_text='ENTREGA DO CADASTRO E IMOBILIZAÇÃO', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='ida',
            field=models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO NA ÁGUA (IDA)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='ide',
            field=models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO NA ESGOTO(IDE)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='idg',
            field=models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO GLOBAL (IDG)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='idr',
            field=models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO REPOSIÇÃO (IDR)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='isap',
            field=models.DecimalField(decimal_places=2, help_text='SERVIÇOS ATENDIDOS NO PRAZO (ISAP)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='justificativa',
            field=models.TextField(max_length=500, verbose_name='Justifique os indicadores informados.'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='seg_capacitacao',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SEGURANÇA E CAPACITAÇÃO'),
        ),
    ]
