# Generated by Django 4.2.4 on 2023-11-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='administrador',
            field=models.CharField(max_length=100, verbose_name='Responsavel da Contratada'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='cadastrado_por',
            field=models.CharField(max_length=100, verbose_name='Cadastrado Por'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Inicio do Contrato'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Inicio do Contrato'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='inserido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inserido em'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='nome_contratada',
            field=models.CharField(max_length=100, verbose_name='Nome da Contratada'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='numemro_contrato',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='r_m',
            field=models.CharField(choices=[('R', 'Interior'), ('M', 'Metropolitana')], max_length=1, verbose_name='Metropolitana/Interior'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='superintendente',
            field=models.CharField(max_length=100, verbose_name='Surperintendente'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inserido em'),
        ),
    ]
