# Generated by Django 4.2.4 on 2023-11-17 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='OS_fotos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordens sem fotos'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='casas_decimais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='serv_2_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Serviços em 2 minutos'),
        ),
    ]
