# Generated by Django 4.2.4 on 2023-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='r_m',
            field=models.CharField(choices=[('R', 'Interior'), ('M', 'Metropolitana')], max_length=1, verbose_name='Diretoria:'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='acidente_trabalho',
            field=models.IntegerField(blank=True),
        ),
    ]
