# Generated by Django 4.2.4 on 2023-11-07 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tb_dados_contrato_administrador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='entrega_cadastro',
            field=models.DecimalField(decimal_places=2, help_text='Entrega do Cadastro E Imobilização', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='idg_interior',
            field=models.DecimalField(decimal_places=2, help_text='Índice de Desempenho Global', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='servicos_arsesp',
            field=models.DecimalField(decimal_places=2, help_text='Serviços Atendidos No Prazo ARSESP', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='idg',
            field=models.DecimalField(decimal_places=2, help_text='INDICE DE DESEMPENHO GLOBAL ', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_referencia_contrato',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='tb_unidades',
            name='ativo',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='SIM', max_length=3, verbose_name='Ativo?'),
        ),
    ]
