# Generated by Django 4.2.4 on 2023-10-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tb_modalidade_metropolitana_entrega_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='staf_1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
