# Generated by Django 4.2.4 on 2023-11-17 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tb_premio_excel_os_fotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_premio_excel',
            name='superintendente',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Superintendencia'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='OS_fotos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Indicador inteiro'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='serv_2_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Indicador inteiro'),
        ),
    ]
