# Generated by Django 4.2.4 on 2023-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tb_dados_contrato_r_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_modalidade_interior',
            name='quantidade_acidentes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de acidentes'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='acidente_trabalho',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='quantidade_colaboradores',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de colaboradores'),
        ),
    ]
