# Generated by Django 4.2.4 on 2023-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tb_referencia_contrato_staf_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='staf_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
