# Generated by Django 4.2.4 on 2023-11-03 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tb_modalidade_interior_quantidade_acidentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_modalidade_metropolitana',
            name='total_cadastro_entregue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de CADASTRO entregue.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tb_modalidade_metropolitana',
            name='total_redes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de Redes executadas.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='acidente_trabalho',
            field=models.DecimalField(decimal_places=2, help_text='indicador de acidentes', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='justificativa',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='quantidade_acidentes',
            field=models.IntegerField(default=0, help_text='Quantidade de acidentes', verbose_name='Quantidade de acidentes'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_interior',
            name='quantidade_colaboradores',
            field=models.IntegerField(default=0, help_text='quantidade de colaboradores no contrato', verbose_name='Quantidade de colaboradores'),
        ),
    ]
