# Generated by Django 4.2.4 on 2023-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tb_dados_contrato_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Fim do Contrato'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='r_m',
            field=models.CharField(choices=[('Interior/Litoral', 'Interior/Litoral'), ('M', 'Metropolitana')], max_length=20, verbose_name='Metropolitana/Interior'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='unidade',
            field=models.CharField(max_length=10, verbose_name='Inserido em'),
        ),
        migrations.AlterField(
            model_name='tb_modalidade_metropolitana',
            name='total_redes',
            field=models.DecimalField(decimal_places=2, help_text='Total de Redes executadas em metros.', max_digits=7, verbose_name='Metros de rede executadas'),
        ),
    ]
