# Generated by Django 4.2.4 on 2023-11-17 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tb_premio_excel_superintendente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='OS_fotos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='casas_decimais',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='original',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='serv_2_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Serviços 2 Minutos'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='superintendente',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Superintendente'),
        ),
    ]
