# Generated by Django 4.2.4 on 2023-11-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tb_dados_contrato_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_dados_contrato',
            name='resp_contratada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsavel Pela Contratada'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='administrador',
            field=models.CharField(max_length=100, verbose_name='Administrador do Contrato'),
        ),
    ]
