# Generated by Django 4.2.4 on 2023-11-17 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tb_premio_excel_os_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='serv_2_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Serviços 2 Minutos'),
        ),
    ]
