# Generated by Django 4.2.4 on 2023-10-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tb_referencia_contrato_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_dados_contrato',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
