# Generated by Django 4.2.4 on 2023-11-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tb_premio_excel_serv_2_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='OS_fotos',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='casas_decimais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='original',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
