# Generated by Django 4.2.4 on 2023-11-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tb_dados_contrato_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='administrador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tb_referencia_contrato',
            name='superintendente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
