# Generated by Django 4.2.4 on 2023-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tb_premio_excel_os_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_premio_excel',
            name='superintendente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Superintendente'),
        ),
    ]
