# Generated by Django 4.2.4 on 2023-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tb_premio_excel_superintendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_premio_excel',
            name='setor',
            field=models.CharField(blank=True, choices=[('Interior', 'Interior'), ('C', 'Capital')], max_length=20, null=True, verbose_name='Capital/Interior'),
        ),
        migrations.AlterField(
            model_name='tb_dados_contrato',
            name='r_m',
            field=models.CharField(choices=[('Interior', 'Interior'), ('C', 'Capital')], max_length=20, verbose_name='Metropolitana/Interior'),
        ),
    ]
